version: '3.8'

services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: kelburgdb
      POSTGRES_USER: kelburguser
      POSTGRES_PASSWORD: database69420!
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  api:
    image: kelburg_api:latest
    container_name: kelburg_api
    env_file:
      - jwt.env
    environment:
      DefaultConnection: /run/secrets/DefaultConnection
      Key: /run/secrets/key
      Issuer: /run/secrets/issuer
      Audience: /run/secrets/audience
    secrets:
      - DefaultConnection
      - key
      - issuer
      - audience
    depends_on:
      - db
    ports:
      - "8080:8080"

secrets:
  DefaultConnection:
    external: true
  key:
    file: ./jwt-env-key
  issuer:
    file: ./jwt-env-issuer
  audience:
    file: ./jwt-env-audience
        
volumes:
  pg_data: