version: '3.8'

services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: kelburgdb
      POSTGRES_USER: kelburguser
      POSTGRES_PASSWORD: database69420!
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  api:
    image: kelburg_api:latest
    environment:
      DefaultConnection: /run/secrets/DefaultConnection
      Key: /run/secrets/Key
      Issuer: /run/secrets/Issuer
      Audience: /run/secrets/Audience
    secrets:
      - DefaultConnection
      - key
      - issuer
      - audience
    depends_on:
      - db
    ports:
      - "8080:8080"

secrets:
  DefaultConnection:
    external: true
  Key:
    external: true
  Issuer:
    external: true
  Audience:
    external: true

volumes:
  pg_data: