version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: kelburg_db
    environment:
      POSTGRES_DB: 
      POSTGRES_USER: 
      POSTGRES_PASSWORD: /run/secrets/db_password
    secrets:
      - db_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    image: localhost:5000/kelburg_api:latest
    container_name: kelburg_api
    depends_on:
      - db
    ports:
      - "8080:80"
        
secrets:
  db_password:
    external: true

volumes:
  db_data: